apiVersion: messaging.knative.dev/v1beta1
kind: KafkaChannel
metadata:
  name: stock-price-channel
  finalizers:
    - kafkachannels.messaging.knative.dev
  labels:
    app: stock
    app.kubernetes.io/component: stock-price-channel
    app.kubernetes.io/instance: stock-price-channel
    app.kubernetes.io/part-of: stock
spec:
  numPartitions: 1
  replicationFactor: 1
